CREATE TABLE "ANGAJAT" (
	"ID_ANGAJAT" 		NUMBER(3,0) NOT NULL,
	"NUME_ANGAJAT"		VARCHAR2(35) NOT NULL,
	"PRENUME_ANGAJAT"	VARCHAR2(60) NOT NULL,
	"LOGINID"			VARCHAR2(5),
	"PAROLA" 			VARCHAR2(255) NOT NULL,
	"NUMAR_TELEFON"		VARCHAR2(10) NOT NULL,
	constraint "ANGAJAT_PK" primary key ("ID_ANGAJAT")
)
/
CREATE SEQUENCE "ANGAJAT_SEQ"
/
CREATE TRIGGER "BI_ANGAJAT"
  BEFORE INSERT ON "ANGAJAT"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_ANGAJAT" is null then
      SELECT "ANGAJAT_SEQ".nextval into :NEW."ID_ANGAJAT" FROM sys.dual;
  END IF;
END;
/
ALTER TABLE "ANGAJAT" ADD CONSTRAINT "ANGAJAT_UK1" unique("LOGIND")
/
CREATE TABLE "SUCURSALA" (
	"ID_SUCURSALA"		NUMBER(3,0) NOT NULL,
	"NUME_SUCURSALA"	VARCHAR2(30) NOT NULL,
	"ORAS_SUCURSALA"	VARCHAR2(30) NOT NULL,
	"JUDET_SUCURSALA"	VARCHAR2(40) NOT NULL,
	"TARA_SUCURSALA"	VARCHAR2(50) NOT NULL,
	"ADRESA_SUCURSALA"	VARCHAR2(60) NOT NULL,
	constraint "SUCURSALA_PK" primary key ("ID_SUCURSALA")
)
/
CREATE SEQUENCE "SUCURSALA_SEQ"
/
CREATE TRIGGER "BI_SUCURSALA"
  BEFORE INSERT ON "SUCURSALA"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_SUCURSALA" is null then
      SELECT "SUCURSALA_SEQ".nextval into :NEW."ID_SUCURSALA" FROM sys.dual;
  END IF;
END;
/
CREATE TABLE "CLIENT" (
	"ID_CLIENT"		NUMBER(3,0) NOT NULL,
	"ID_CONT"		NUMBER(6,0) NOT NULL,
	"NUME_CLIENT"	VARCHAR2(30) NOT NULL,
	"PRENUME_CLIENT" VARCHAR2(60) NOT NULL,
	"LOGIND"		VARCHAR2(8),
	"PAROLA"		VARCHAR2(255) NOT NULL,
	"STATUS_CONT"	VARCHAR2(7)	NOT NULL,
	"ORAS_CLIENT"	VARCHAR2(60) NOT NULL,
	"JUDET_CLIENT"  VARCHAR2(60) NOT NULL,
	"TARA_CLIENT"	VARCHAR2(60) NOT NULL,
	"NUMAR_TELEFON" VARCHAR2(10) NOT NULL,
	constraint "CLIENT_PK" primary key ("ID_CLIENT")
)
/
CREATE SEQUENCE "CLIENT_SEQ"
/
CREATE TRIGGER "BI_CLIENT"
  BEFORE INSERT ON "CLIENT"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_CLIENT" is null then
      SELECT "CLIENT_SEQ".nextval into :NEW."ID_CLIENT" FROM sys.dual;
  END IF;
END;
/
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_FK" FOREIGN KEY ("ID_CONT")
REFERENCES "CONT" ("ID_CONT") ON DELETE CASCADE
/
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_UK1" unique ("LOGINID")
/
CREATE TABLE "CONT" (
	"ID_CONT" NUMBER(6,0),
	"ID_CLIENT" NUMBER(3,0) NOT NULL,
	"STATUS_CONT" VARCHAR2(7) NOT NULL,
	"DATA_DESCHIDERE" DATE NOT NULL,
	"TIP_CONT" VARCHAR2(20) NOT NULL,
	"BALANTA" FLOAT(10) NOT NULL,
	"ID_SUCURSALA" NUMBER(3,0) NOT NULL,
	constraint "CONT_PK" primary key ("ID_CONT")
)
/
ALTER TABLE "CONT" ADD CONSTRAINT "CONT_FK" FOREIGN KEY ("ID_CLIENT")
REFERENCES "CLIENT" ("ID_CLIENT") ON DELETE CASCADE
/
ALTER TABLE "CONT" ADD CONSTRAINT "CONT_FK1" FOREIGN KEY ("ID_SUCURSALA")
REFERENCES "SUCURSALA" ("ID_SUCURSALA") ON DELETE CASCADE
/
CREATE TABLE "BENEFICIAR" (
	"ID_BENEFICIAR" NUMBER(3,0) NOT NULL,
	"NUME_BENEFICIAR" VARCHAR2(30) NOT NULL,
	"PRENUME_BENEFICIAR" VARCHAR2(60) NOT NULL,
	"ID_CONT" NUMBER(6,0) NOT NULL,
	"ID_BANCA" NUMBER(3,0) NOT NULL,
	"TIP_CONT" VARCHAR2(25) NOT NULL,
	constraint "BENEFICIAR_PK" primary key ("ID_BENEFICIAR")
)
/
CREATE SEQUENCE "BENEFICIAR_SEQ"
/
CREATE TRIGGER "BI_BENEFICIAR"
  BEFORE INSERT ON "BENEFICIAR"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_BENEFICIAR" is null then
      SELECT "BENEFICIAR_SEQ".nextval into :NEW."ID_BENEFICIAR" FROM sys.dual;
  END IF;
END;
/
ALTER TABLE "BENEFICIAR" ADD CONSTRAINT "BENEFICIAR_FK1" FOREIGN KEY ("ID_BANCA")
REFERENCES "SUCURSALA" ("ID_SUCURSALA") ON DELETE CASCADE
/
CREATE TABLE "TRANZACTIE" (
	"ID_TRANZACTIE" NUMBER(3,0) NOT NULL,
	"DATA_TRANZACTIE" DATE NOT NULL,
	"ID_BENEFICIAR" NUMBER(6,0) NOT NULL,
	"ID_CLIENT" NUMBER(6,0) NOT NULL,
	"SUMA" FLOAT(10) NOT NULL,
	"ID_ANGAJAT" NUMBER(3,0) NOT NULL,
	constraint "TRANZACTIE_PK" primary key("ID_TRANZACTIE")
)
/
CREATE SEQUENCE "TRANZACTIE_SEQ"
/
CREATE TRIGGER "BI_TRANZACTIE"
  BEFORE INSERT ON "TRANZACTIE"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_TRANZACTIE" is null then
      SELECT "TRANZACTIE_SEQ".nextval into :NEW."ID_TRANZACTIE" FROM sys.dual;
  END IF;
END;
/
ALTER TABLE "TRANZACTIE" ADD CONSTRAINT "TRANZACTIE_FK1" FOREIGN KEY ("ID_CLIENT")
REFERENCES "CLIENT" ("ID_CLIENT")
/
ALTER TABLE "TRANZACTIE" ADD CONSTRAINT "TRANZACTIE_FK2" FOREIGN KEY ("ID_ANGAJAT")
REFERENCES "ANGAJAT" ("ID_ANGAJAT")
/
CREATE TABLE "TIPIMPRUMUT" (
	"TIP_IMPRUMUT" VARCHAR2(50) NOT NULL,
	"SUMA_MINIMA" FLOAT(10) NOT NULL,
	"SUMA_MAXIMA" FLOAT(10) NOT NULL,
	"STATUS" VARCHAR2(20) NOT NULL,
	CONSTRAINT "TIPIMPRUMUT_PK" PRIMARY KEY ("TIP_IMPRUMUT")
)
/
CREATE SEQUENCE "TIPIMPRUMUT_SEQ"
/
CREATE TRIGGER "BI_TIPIMPRUMUT"
  BEFORE INSERT ON "TIPIMPRUMUT"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_TIPIMPRUMUT" is null then
      SELECT "TIPIMPRUMUT_SEQ".nextval into :NEW."ID_TIPIMPRUMUT" FROM sys.dual;
  END IF;
END;
/
CREATE TABLE "IMPRUMUT" (
	"ID_IMPRUMUT" NUMBER(3,0) NOT NULL,
	"ID_CONT" NUMBER(6,0) NOT NULL,
	"TIP_IMPRUMUT" VARCHAR2(50) NOT NULL,
	"SUMA_IMPRUMUT" FLOAT(10) NOT NULL,
	"PERIOADA_IMPRUMUT" NUMBER(5,0) NOT NULL,
	"MOTIV_IMPRUMUT" VARCHAR2(255) NOT NULL,
	"DATA_INCEPUT" DATE NOT NULL,
	CONSTRAINT "IMPRUMUT_PK" PRIMARY KEY ("ID_IMPRUMUT")
)
/
CREATE SEQUENCE "IMPRUMUT_SEQ"
/
CREATE TRIGGER "BI_IMPRUMUT"
  BEFORE INSERT ON "IMPRUMUT"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_IMPRUMUT" is null then
      SELECT "IMPRUMUT_SEQ".nextval into :NEW."ID_IMPRUMUT" FROM sys.dual;
  END IF;
END;
/
ALTER TABLE "IMPRUMUT" ADD CONSTRAINT "IMPRUMUT_FK" FOREIGN KEY ("TIP_IMPRUMUT")
REFERENCES "TIPIMPRUMUT" ("TIP_IMPRUMUT")
/
ALTER TABLE "IMPRUMUT" ADD CONSTRAINT "IMPRUMUT_FK1" FOREIGN KEY ("ID_CONT")
REFERENCES "CONT" ("ID_CONT")
/
CREATE TABLE "PLATA_IMPRUMUT" (
	"ID_PLATA" NUMBER(3,0) NOT NULL,
	"ID_IMPRUMUT" NUMBER(3,0) NOT NULL,
	"SUMA_PLATA" FLOAT(10) NOT NULL,
	"BALANTA" FLOAT(10),
	CONSTRAINT "PLATA_IMPRUMUT_PK" PRIMARY KEY ("ID_PLATA")
)
/
CREATE SEQUENCE "PLATA_IMPRUMUT_SEQ"
/
CREATE TRIGGER "BI_PLATA_IMPRUMUT"
  BEFORE INSERT ON "PLATA_IMPRUMUT"
  FOR EACH ROW
BEGIN
  IF:NEW."ID_PLATA" is null then
      SELECT "PLATA_IMPRUMUT_SEQ".nextval into :NEW."ID_PLATA" FROM sys.dual;
  END IF;
END;
/
ALTER TABLE "PLATA_IMPRUMUT" ADD CONSTRAINT "PLATA_IMPRUMUT_FK"  FOREIGN KEY ("ID_IMPRUMUT")
REFERENCES "IMPRUMUT" ("ID_IMPRUMUT") ON DELETE CASCADE
/