CREATE TABLE  "CARTE" 
   (    "ID_CARTE" NUMBER NOT NULL ENABLE, 
    "NUME_CARTE" VARCHAR2(50) NOT NULL ENABLE, 
    "NUME_AUTOR1" VARCHAR2(50) NOT NULL ENABLE, 
    "PRENUME_AUTOR1" VARCHAR2(50) NOT NULL ENABLE, 
    "NUME_AUTOR2" VARCHAR2(50), 
    "PRENUME_AUTOR2" VARCHAR2(50), 
    "CATEGORIE_CARTE" VARCHAR2(30) NOT NULL ENABLE, 
    "ISBN_CARTE" VARCHAR2(13) NOT NULL ENABLE, 
    "RAFT_CARTE" VARCHAR2(4), 
    "AN_CARTE" NUMBER(4,0) NOT NULL ENABLE, 
    "EDITURA_CARTE" VARCHAR2(30) NOT NULL ENABLE, 
    "DESCRIERE_CARTE" VARCHAR2(255), 
    "COPERTA_CARTE" BLOB NOT NULL ENABLE, 
    "FILENAME" VARCHAR2(255), 
    "MIMETYPE" VARCHAR2(255), 
    "LAST_UPDATE_DATE" DATE, 
     CONSTRAINT "CARTE_PK" PRIMARY KEY ("ID_CARTE") ENABLE
   )
/
CREATE TABLE  "CATEGORIE" 
   (    "ID_CATEGORIE" NUMBER NOT NULL ENABLE, 
    "NUME_CATEGORIE" VARCHAR2(30) NOT NULL ENABLE, 
     CONSTRAINT "CATEGORIE_PK" PRIMARY KEY ("ID_CATEGORIE") ENABLE
   )
/
CREATE TABLE  "EDITURA" 
   (    "ID_EDITURA" NUMBER NOT NULL ENABLE, 
    "NUME_EDITURA" VARCHAR2(30) NOT NULL ENABLE, 
    "ADRESA_EDITURA" VARCHAR2(155) NOT NULL ENABLE, 
    "TELEFON_EDITURA" VARCHAR2(13) NOT NULL ENABLE, 
    "FAX_EDITURA" VARCHAR2(20), 
    "WEB_EDITURA" VARCHAR2(50) NOT NULL ENABLE, 
     CONSTRAINT "EDITURA_PK" PRIMARY KEY ("ID_EDITURA") ENABLE
   )
/
CREATE TABLE  "IMPRUMUT" 
   (    "ID_IMPRUMUT" NUMBER NOT NULL ENABLE, 
    "NUME_CARTE" VARCHAR2(60) NOT NULL ENABLE, 
    "NUME_PERSOANA" VARCHAR2(30) NOT NULL ENABLE, 
    "PRENUME_PERSOANA" VARCHAR2(60) NOT NULL ENABLE, 
    "DATA" DATE, 
     CONSTRAINT "IMPRUMUT_PK" PRIMARY KEY ("ID_IMPRUMUT") ENABLE
   )
/
CREATE UNIQUE INDEX  "SYS_IL0000024371C00013$$" ON  "CARTE" (
/
 CREATE SEQUENCE   "IMPRUMUT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EDITURA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "CATEGORIE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "CARTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_IMPRUMUT" 
  before insert on "IMPRUMUT"               
  for each row  
begin   
  if :NEW."ID_IMPRUMUT" is null then 
    select "IMPRUMUT_SEQ".nextval into :NEW."ID_IMPRUMUT" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_IMPRUMUT" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EDITURA" 
  before insert on "EDITURA"               
  for each row  
begin   
  if :NEW."ID_EDITURA" is null then 
    select "EDITURA_SEQ".nextval into :NEW."ID_EDITURA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_EDITURA" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_CATEGORIE" 
  before insert on "CATEGORIE"               
  for each row  
begin   
  if :NEW."ID_CATEGORIE" is null then 
    select "CATEGORIE_SEQ".nextval into :NEW."ID_CATEGORIE" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_CATEGORIE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_CARTE" 
  before insert on "CARTE"               
  for each row  
begin   
  if :NEW."ID_CARTE" is null then 
    select "CARTE_SEQ".nextval into :NEW."ID_CARTE" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_CARTE" ENABLE
/
